---
title: "2. Feladatok"
subtitle: |
  | Kurzus: Programozás I. 6. óra
author: |
  | Oktató: Balogh Kitti kttblgh@gmail.com
date: "Időpont: 2017-03-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---

## I. Feladat
1. A ```lesson-06``` projekt ```src``` mappájában nyiss egy új R szkriptet ```prog1_lesson06_part02_Feladatok.R``` néven, aminek a fejléce tartalmazza a következőket: 
    - fájl címe (Feladatok)
    - kurzus neve (Programozás I.)
    - óra sorszáma (6. óra)
    - neved
    - dátum (2017-03-21)
2. Figyelj, hogy kommentelj, és minél jobban betartsd a R kódírási stílusra vonatkozó irányelveket!

---

## II. feladat
1. Olvasd be ```data``` mappából a ```gapminder.csv```-t ```gm``` néven.
2. Ábrázold a születéskor várható élettartamot (```lifeExp``` oszlop) hisztogramon, rajzold rá a sűrűségfüggvény görbét és az átlagot egy függőleges vonallal! A hisztogram színe legyen ```grey65```, a sűrűség görbe színe pedig ```aquamarine```. A plot hasonlítson minél jobban a kimentett ```fig/part02/exercise_II_2.png``` ábrára!
3. Készíts egy oszlopdiagramot a kontinensenkénti átlagos születéskor várható élettartammal. Az oszlopok színe legyen egy paletta az ```#999999, #E69F00, #56B4E9, #009E73, #0072B2``` színkódú színekkel. [Itt](http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/){target="_blank"} találsz róla infót, hogy hogyan tudsz manuálisan palettát beállítani, ha ```ggplot2```-vel dolgozol, és [itt](http://www.r-tutor.com/elementary-statistics/qualitative-data/bar-graph){target="_blank"}, ha a ```base``` package-gel. A plot hasonlítson minél jobban a kimentett ```fig/part02/exercise_II_3.png``` ábrára!
4. Készíts egy szórásdiagramot a születéskor várható élettartamról 2007-ben. Az alapegységek legyenek az országok, de a színezés legyen kontinensenként. Használd az előző palettát a színezéshez. Az egyes kontinensek országainak pontfelhőjére illessz lineáris regressziós egyenest! Az y-tengelyt tedd logaritmikus skálára (log10). A diagram hasonlítson minél jobban a kimentett ```fig/part02/exercise_II_4.png``` ábrára!
5. Ábrázold a kontinensenkénti születéskor várható élettartamot 1952-től 2007-ig vonaldiagrammal. Használd az előző palettát a színezéshez. A plot hasonlítson minél jobban a kimentett ```fig/part02/exercise_II_5.png``` ábrára!
6. Ábrázold az országonkénti átlagos születéskor várható élettartam és az átlagos egy főre jutó GDP kapcsolatát szórásdiagramon! Az alapegységek legyenek az országok, de a pontok színezése legyen kontinensenként. Használd az előző palettát a színezéshez. Feliratozd a pontokat az országok nevével. Az y-tengelyt tedd logaritmikus skálára (log10). A plot hasonlítson minél jobban a kimentett ```fig/part02/exercise_II_6.png``` ábrára!

---
